apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dotnet-todos-api-catalog-info
  description: Catalog jeff for DotNet Todos App
spec:
  targets:
    - ./dotnet-todos-api/dotnet-todos-component.yaml
    - ./dotnet-todos-api/dotnet-todos-api.yaml
